---
title: "Final_project_script"
output: html_document
date: "2026-04-16"
---

# ----------LOAD THE PACKAGES FOR PROJECT------------
```{r}
# install.packages("tidyverse")
# install.packages("janitor")
# install.packages("lubridate")
# install.packages("here")
# install.packages("vip")
# install.packages("xgboost")
# install.packages("doParallel")
# install.packages("shapviz")
# unlink("/home/cja04613/R/x86_64-pc-linux-gnu-library/4.5/00LOCK-survival", recursive = TRUE)
# install.packages("recipes")
# install.packages(c("purrr", "rsample"))
# install.packages("resample")
# # install.packages("finetune")
# install.packages("purrr")




#| message: false
#| warning: false


#.libPaths(c("/work/crss8030/instructor_data/shared_R_libs", .libPaths()))
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
library(vip)          
library(xgboost)      
library(ranger)       
library(doParallel)   
library(shapviz)
library(recipes)
library(resample)
library(finetune)     
library(parsnip)
library(daymetr)
#library(caret)   

#knitr::purl("finalproject_code.qmd", output = "finalproject_script.R", documentation = 0)

```

# ----------LOAD TRAINING DATA------------
```{r}
#| message: false
#| warning: false

#getwd()
s#etwd("/home/cja04613/2026dsa_finalproject_group12")

train_meta <- read_csv("../data/training/training_meta.csv") %>% 
  janitor::clean_names() 
train_trait <- read_csv("../data/training/training_trait.csv") %>% 
  janitor::clean_names() 
train_soil <- read_csv("../data/training/training_soil.csv") %>% 
  janitor::clean_names()

```



<!-- ```{r} -->
<!-- daymet_one <- download_daymet(site = train_meta$site[1],  -->
<!--                               lat = train_meta$latitude[1], -->
<!--                               lon = train_meta$longitude [1], -->
<!--                               start = train_meta$year[1], -->
<!--                               end = train_meta$year[1], -->
<!--                               simplify = T -->
<!--                               ) -->
<!-- ``` -->



<!-- ```{r} -->
<!--  train_meta <- train_meta %>% filter (latitude >= 14.0749 & latitude <= 82.9143 & -->
<!--                   longitude >= -178.133 & longitude <= -53.0567)# information on daymet website(https://www.earthdata.nasa.gov/data/catalog/ornl-cloud-daymet-daily-v4r1-2129-4.1) shows that US is within this coordinates -->


<!-- ``` -->


<!-- ```{r} -->
<!-- train_meta_weather <- train_meta %>% -->
<!--   mutate(weather = pmap(list(.y = year, -->
<!--                              .site = site, -->
<!--                              .lat = latitude, -->
<!--                              .lon = longitude), -->
<!--                         function(.y, .site, .lat, .lon) -->
<!--                           download_daymet( -->
<!--                             site = .site, -->
<!--                             lat = .lat, -->
<!--                             lon = .lon, -->
<!--                             start = .y, -->
<!--                             end = .y, -->
<!--                             simplify = T, -->
<!--                             silent = T -->
<!--                           ) %>% -->
<!--                           rename(.year = year, -->
<!--                                  .site = site -->
<!--                                  ) -->


<!--                         )) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- train_weather <- train_meta_weather %>%  -->
<!--   rename(lat = latitude, -->
<!--          lon = longitude) %>%  -->
<!--   unnest(weather) %>%  -->
<!--   pivot_wider(names_from = measurement, -->
<!--               values_from = value -->
<!--               ) %>%  -->
<!--   janitor::clean_names() %>%  -->
<!--   unnest(dayl_s: vp_pa) %>%  -->
<!--   dplyr::select(site, year, lon, lat,yday, dayl_s:vp_pa) -->

<!-- write_csv(train_weather, -->
<!--           "../data/train_weather.csv" -->
<!--           ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- train_weather %>% -->
<!--   pivot_longer(cols = dayl_s:vp_pa) %>% -->
<!--   ggplot(aes(x = value)) + -->
<!--   geom_density() + -->
<!--   facet_wrap(~name, scales = "free") -->
<!-- ``` -->


# -------------MERGE------------

```{r}
#| message: false
#| warning: false

train_weather <- read_csv("../data/train_weather.csv")

train_full <- train_trait %>%
  left_join(train_weather, by = c("site", "year")) %>%
  left_join(train_soil, by = c("site", "year")) #%>% 
  mutate(across(soilp_h:soilp_ppm, as.numeric))

  summary(train_full)
```

```{r}
train_full_month <- train_full %>%
  # Selecting needed variables
  dplyr::select(year, site, lat, lon,
                yield_mg_ha,
                grain_moisture,
                yday,
                dayl.s = dayl_s, 
                prcp.mm = prcp_mm_day,
                srad.wm2 = srad_w_m_2, 
                tmax.c = tmax_deg_c, 
                tmin.c = tmin_deg_c,
                vp.pa = vp_pa
                ) %>%
  # Creating a date class variable  
  mutate(date_chr = paste0(year, "/", yday)) %>%
  mutate(date = as.Date(date_chr, "%Y/%j")) %>%
  # Extracting month from date  
  mutate(month = month(date)) %>%
  mutate(month_abb = month(date, label = T))
```


```{r}
train_full_month_sum <- train_full_month %>%
  group_by(year, site, month_abb, yield_mg_ha, grain_moisture,) %>%
  summarise(across(.cols = c(dayl.s,
                             srad.wm2,
                             tmax.c,
                             tmin.c,
                             vp.pa
                             ),
                   .fns = mean, 
                   .names = "mean_{.col}"
                   ),
            across(.cols = prcp.mm,
                   .fns = sum,
                   .names = "sum_{.col}"
                   )
            ) %>%
  ungroup()
```


```{r}
train_full_month_sum_wide <- train_full_month_sum %>%
  pivot_longer(mean_dayl.s:sum_prcp.mm)%>%
  mutate(varname = paste0(name, "_",month_abb)) %>%
  dplyr::select(-name, -month_abb) %>% #another way of excluding some column
  pivot_wider(names_from = varname,
              values_from = value
              ) %>%
  # Rounding to one decimal point
  mutate(across(c(3:82), ~round(., 1)))
```


# ----------LOAD TESTING DATA------------
```{r}
#| message: false
#| warning: false

test_meta <- read_csv("../data/testing/testing_meta.csv") %>% 
  janitor::clean_names() 
test_soil <- read_csv("../data/testing/testing_soil.csv") %>% 
  janitor::clean_names() 
test_sub  <- read_csv("../data/testing/testing_submission.csv") %>% 
  janitor::clean_names() 

head(test_sub)
head(test_meta)
head(test_soil)

table(test_meta$previous_crop)
summary(test_soil)
summary(test_sub)
```


<!-- ```{r} -->
<!--  test_meta <- test_meta %>% filter (latitude >= 14.0749 & latitude <= 82.9143 & -->
<!--                   longitude >= -178.133 & longitude <= -53.0567)# information on daymet website(https://www.earthdata.nasa.gov/data/catalog/ornl-cloud-daymet-daily-v4r1-2129-4.1) shows that US is within this coordinates -->


<!-- ``` -->


<!-- ```{r} -->
<!-- test_meta_weather <- test_meta %>% -->
<!--   mutate(weather = pmap(list(.y = year, -->
<!--                              .site = site, -->
<!--                              .lat = latitude, -->
<!--                              .lon = longitude), -->
<!--                         function(.y, .site, .lat, .lon) -->
<!--                           download_daymet( -->
<!--                             site = .site, -->
<!--                             lat = .lat, -->
<!--                             lon = .lon, -->
<!--                             start = .y, -->
<!--                             end = .y, -->
<!--                             simplify = T, -->
<!--                             silent = T -->
<!--                           ) %>% -->
<!--                           rename(.year = year, -->
<!--                                  .site = site -->
<!--                                  ) -->


<!--                         )) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- test_weather <- test_meta_weather %>% -->
<!--   rename(lat = latitude, -->
<!--          lon = longitude) %>% -->
<!--   unnest(weather) %>% -->
<!--   pivot_wider(names_from = measurement, -->
<!--               values_from = value -->
<!--               ) %>% -->
<!--   janitor::clean_names() %>% -->
<!--   unnest(dayl_s: vp_pa) %>% -->
<!--   dplyr::select(site, year, lon, lat,yday, dayl_s:vp_pa) -->

<!-- write_csv(test_weather, -->
<!--           "../data/test_weather.csv" -->
<!--           ) -->
<!-- ``` -->


# -------------MERGE------------

```{r}
#| message: false
#| warning: false

test_weather <- read_csv("../data/test_weather.csv")

test_full <- test_weather %>%
  left_join(train_soil, by = c("site", "year")) #%>% 
  mutate(across(soilp_h:soilp_ppm, as.numeric))

  summary(train_full)
```

```{r}
test_full_month <- test_full %>%
  # Selecting needed variables
  dplyr::select(year, site, lat, lon,
                yday,
                dayl.s = dayl_s, 
                prcp.mm = prcp_mm_day,
                srad.wm2 = srad_w_m_2, 
                tmax.c = tmax_deg_c, 
                tmin.c = tmin_deg_c,
                vp.pa = vp_pa
                ) %>%
  # Creating a date class variable  
  mutate(date_chr = paste0(year, "/", yday)) %>%
  mutate(date = as.Date(date_chr, "%Y/%j")) %>%
  # Extracting month from date  
  mutate(month = month(date)) %>%
  mutate(month_abb = month(date, label = T))
```


```{r}
test_full_month_sum <- test_full_month %>%
  group_by(year, site, month_abb) %>%
  summarise(across(.cols = c(dayl.s,
                             srad.wm2,
                             tmax.c,
                             tmin.c,
                             vp.pa
                             ),
                   .fns = mean, 
                   .names = "mean_{.col}"
                   ),
            across(.cols = prcp.mm,
                   .fns = sum,
                   .names = "sum_{.col}"
                   )
            ) %>%
  ungroup()
```


```{r}
test_full_month_sum_wide <- train_full_month_sum %>%
  pivot_longer(mean_dayl.s:sum_prcp.mm)%>%
  mutate(varname = paste0(name, "_",month_abb)) %>%
  dplyr::select(-name, -month_abb) %>% #another way of excluding some column
  pivot_wider(names_from = varname,
              values_from = value
              ) %>%
  # Rounding to one decimal point
  mutate(across(c(3:9), ~round(., 1)))
```


```{r}
# Create recipe for data preprocessing
weather_recipe <- recipe(yield_mg_ha ~ ., data = train_full_month_sum_wide) %>% # Remove identifier columns and months not in growing season
  step_rm(
    year,       # Remove year identifier
    site,       # Remove site identifier
    matches("Jan|Feb|Mar|Apr|Nov|Dec")  # Remove non-growing season months
  ) %>% 

  # updating the role of the 2 columns as ID, so they arenot used as predictors
update_role(c(year, site), new_role = "ID")
```

```{r}
weather_prep <- weather_recipe %>% 
  prep()
```

```{r}
xgb_spec <- #Specifying XgBoost as our model type, asking to tune the hyperparameters
  boost_tree(
   # Total number of boosting iterations
  trees = tune(),
         # Maximum depth of each tree
  tree_depth = tune(),
             # Minimum samples required to split a node
  min_n = tune(),
        # Step size shrinkage for each boosting step
   learn_rate = tune()
  ) %>% 
        #specify engine 
  set_engine("xgboost") %>% 
       # Set to mode
  set_mode("regression")
xgb_spec
```


```{r}

library(rsample)

set.seed(235) 
resampling_foldcv <- vfold_cv(train_full_month_sum_wide, # Create 5-fold cross-validation resampling object from training data
                              v = 10)


# Create leave one year out cv object from the sampling data
resampling_fold_loyo <- group_vfold_cv(train_full_month_sum_wide,
                                       group = year
                                       )

# Create leave one location out cv object from the sampling data
resampling_fold_loso <- group_vfold_cv(train_full_month_sum_wide,
                                       group = site
                                       )


resampling_foldcv
resampling_foldcv$splits[[1]]
```

```{r}

library(dials)

xgb_grid <- grid_latin_hypercube(
  tree_depth(),
  min_n(),
  learn_rate(),
  trees(),
  size = 10
)

```


```{r}
# lets look into our current environment to see the available cores
n_cores <- as.numeric(Sys.getenv("SLURM_CPUS_ON_NODE"))

if (is.na(n_cores)) n_cores <- parallel::detectCores() - 1

# Start the Cluster
cl <- makePSOCKcluster(n_cores)

registerDoParallel(cl)

cat(paste0("\nFound and registered ", n_cores, " cores to work with\n"))


```

```{r}
final_spec <- boost_tree(
  trees = best_r2$trees,           # Number of boosting rounds (trees)
  tree_depth = best_r2$tree_depth, # Maximum depth of each tree
  min_n = best_r2$min_n,           # Minimum number of samples to split a node
  learn_rate = best_r2$learn_rate  # Learning rate (step size shrinkage)
) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

final_spec
```



```{r}
all_data <- bind_rows(
  train_full_month %>% mutate(split = "train"),
  test_full_month  %>% mutate(split = "test")
)
```


```{r}
all_features <- all_data %>%
  group_by(year, site, month_abb, split) %>%
  summarise(
    yield_mg_ha = mean(yield_mg_ha, na.rm = T),
    grain_moisture = mean(grain_moisture, na.rm = T),

    across(
      c(dayl.s, srad.wm2, tmax.c, tmin.c, vp.pa),
      mean
    ),

    prcp.mm = sum(prcp.mm),

    .groups = "drop"
  )
```

```{r}
all_wide <- all_features %>%
  pivot_wider(
    names_from = month_abb,
    values_from = c(
      dayl.s, srad.wm2, tmax.c, tmin.c, vp.pa, prcp.mm
    ),
    names_glue = "{.value}_{month_abb}"
  )
```

```{r}
train_data <- all_wide %>% filter(split == "train") %>% select(-split)
test_data  <- all_wide %>% filter(split == "test")  %>% select(-split)
```

```{r}
weather_recipe <- recipe(yield_mg_ha ~ ., data = train_data) %>%
  step_rm(year, site) %>%
  step_impute_mean(all_predictors())
```


```{r}
final_fit <- workflow() %>%
  add_recipe(weather_recipe) %>%
  add_model(final_spec) %>%
  fit(data = train_data)
```

```{r}
test_predictions <- test_data %>%
  bind_cols(predict(final_fit, new_data = test_data)) %>% 
  dplyr::select(year, site, yield_mg_ha = .pred)
```



